BestRestaurants/Models/BestRestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurants.Models
{
  public class BestRestaurantsContext : DbContext
  {
    public virtual DbSet<Cuisine> Cuisines { get; set; }
    public DbSet<Restaurant> Restaurants { get; set; }
    // public virtual DbSet<Restaurant> Restaurants { get; set; }
    // public DbSet<Review> Reviews { get; set; }

    public BestRestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

BestRestaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant> ();
    }

    public int CuisineId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurants/Models/Restaurant.cs
// using System.Collections.Generic;

namespace BestRestaurants.Models
{
  public class Restaurant
  {
    // public Restaurant()
    // {
    //   this.Review = new List<Review> ();
    // }

    public int RestaurantId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Address { get; set; }
    public int CuisineId { get; set; }

    public virtual Cuisine Cuisine { get; set; }
    // public virtual ICollection<Review> Reviews { get; set; }
  }
}

BestRestaurants/Models/Review.cs
namespace BestRestaurants.Models
{
  public class Review
  {
    public int ReviewId { get; set; }
    public string ReviewText { get; set; }
    public int RestaurantId { get; set; }
    public virtual Restaurant Restaurant { get; set; }

  }
}

BestRestaurants/Controllers/CuisineController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using BestRestaurants.Models;
using System.Linq;

namespace BestRestaurants.Controllers
{
  public class CuisineController : Controller
  {
    private readonly BestRestaurantsContext _db;
    public CuisineController(BestRestaurantsContext db)
    {
      _db = db;
    }
    
    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      ViewBag.thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      ViewBag.restaurants = _db.Restaurants.Where(restaurant => restaurant.CuisineId == id).ToList();
      // List<Restaurant>
      // Dictionary<string, dynamic> detailsModel = new Dictionary<string, dynamic>();
      // detailsModel.Add("thisCuisine", thisCuisine);
      // detailsModel.Add("restaurant", model);

      return View();
    }

    public ActionResult Edit(int id)
    {
      var thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BestRestaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BestRestaurants.Controllers
{
  public class HomeController: Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
  
}

BestRestaurants/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BestRestaurants.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace BestRestaurants.Controllers
{
  public class RestaurantController : Controller
  {
    private readonly BestRestaurantsContext _db;
    
    public RestaurantController(BestRestaurantsContext db)
    {
      _db = db;
    }
    
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }

  }
}

BestRestaurants/Views/Cuisine/Create.cshtml
@model BestRestaurants.Models.Cuisine

<h1> Add a new Cuisine </h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new Cuisine" />
}

<p>@Html.ActionLink("Show All Cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Delete.cshtml
@model BestRestaurants.Models.Cuisine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete Selected Cuisine" />
}

<p>@Html.ActionLink("Show All Cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Details.cshtml
@using BestRestaurants.Models;

<h2>Cuisine Details: @ViewBag.thisCuisine.Name</h2>
<hr />

<ol>
@foreach(Restaurant restaurant in ViewBag.restaurants)
{
  <li>@restaurant.Name</li>
}
</ol>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = ViewBag.thisCuisine.CuisineId })</p>
<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = ViewBag.thisCuisine.CuisineId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

BestRestaurants/Views/Cuisine/Edit.cshtml
@model BestRestaurants.Models.Cuisine

<h1> Edit Selected Cuisine: @Html.DisplayFor(model => model.Name)</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <input type="submit" value="Update" />
}

<p>@Html.ActionLink("Back - View all Cuisines", "Index")</p>

BestRestaurants/Views/Cuisine/Index.cshtml
@using BestRestaurants.Models;

<h1> Cuisines </h1>

@if(@Model.Count == 0)
{
  <h3> No Cuisines Available</h3>
}

<ul>
  @foreach(Cuisine cuisine in Model)
  {
    <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId })</li>
  }
</ul>

<p>@Html.ActionLink("Create new cuisine", "Create")</p>
<p>@Html.ActionLink("Add a new Restaurant", "Create", "Restaurant")</p>

BestRestaurants/Views/Home/Index.cshtml
<h1> Homepage </h1>

<p>@Html.ActionLink("See All cuisine", "Index", "Cuisine")</p>
<p>@Html.ActionLink("Add a new Restaurant", "Create", "Restaurant")</p>

BestRestaurants/Views/Restaurant/Create.cshtml
@model BestRestaurants.Models.Restaurant

<h4>Add a new Restaurant</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br />

  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <br />

  @Html.LabelFor(model => model.Address)
  @Html.TextBoxFor(model => model.Address)
  <br />

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")
  <br />

  <input type="submit" value="Add new item" class="btn btn-default" />
}
<p>@Html.ActionLink("Show all Cuisine", "Index", "Cuisine")</p>

BestRestaurants/Views/Restaurant/Index.cshtml
@using BestRestaurants.Models;
@model List<BestRestaurants.Models.Restaurant>;

<h1> Restaurants </h1>

@if (@Model.Count == 0)
{
  <h3>No items have been added yet!</h3>
} 

<ol>
@foreach (Restaurant restaurant in Model)
{
  <li>@restaurant.Name</li>
}
</ol>

<p>@Html.ActionLink("Go Back To Home", "Index", "Home")</p>